### ISSUE TITLE
Dude, I think you need some bling

### ISSUE THREAD

**Issue by dancooney** [FredCashoon/FredCashoon.github.io#5]
some way to make the workshop shine!  What do you think?

**Comment by FredCashoon** [comment]
**YEAH!** I *totally* agree!

**Comment by FredCashoon** [comment]
#YEAH

**Comment by FredCashoon** [comment]
Do you mean physically, or on the web page?

**Comment by dancooney** [comment]
oh, website


Dan Cooney

**Comment by FredCashoon** [comment]
Okay, that is doable.

**Comment by FredCashoon** [comment]
I'll leave this issue open until I have styled it up.

**Comment by FredCashoon** [comment]
<hr />

**Comment by FredCashoon** [comment]
<hr />
<hr />
<hr />
